name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
          pip install -r requirements.txt

    - name: Run tests
      run: |
          python ladino/ladinadores.py

  generate:
    runs-on: ubuntu-latest
    name: Generate HTML
    needs: [test]

    steps:
    - name: Generate HTML
      env:
         PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        curl -X POST \
             -H "Authorization: token $PERSONAL_ACCESS_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/kantoniko/ladino-diksionaryo-generated/actions/workflows/ci.yml/dispatches \
             -d '{"ref":"main"}' | tee out.txt
        if [ -s out.txt ]
        then
            exit 1
        else
            exit 0
        fi


